## Geometry Analysis Project Solution
### August 9, 2019

In [3]:
# Could have been solved using genfromtxt or readline
import numpy
import os

file_location = os.path.join('data', 'water.xyz')
xyz_file = numpy.genfromtxt(fname = file_location, skip_header = 2, dtype = 'unicode')
# you must use skip header to get rid of lines that don't contain the same number of columns

# Separate data types

symbols = xyz_file[:,0] #symbols are already strings
coordinates = xyz_file[:,1:]

#recast the coordinates as floats

coordinates = coordinates.astype(numpy.float)

# Need to calculate the distance from every atom to every other atom, using a nest for loop
# For the nested for loop, both loops count over the same things

num_atoms = len(symbols)

for num1 in range(0,num_atoms):
    for num2 in range(0,num_atoms):
        x_distance = coordinates[num1,0] - coordinates[num2,0]
        y_distance = coordinates[num1,1] - coordinates[num2,1]
        z_distance = coordinates[num1,2] - coordinates[num2,2]
        bond_length_12 = numpy.sqrt(x_distance**2 + y_distance**2 + z_distance**2)
        if bond_length_12 > 0 and bond_length_12 < 1.5: # to not print the self-self measurements
            print(F'{symbols[num1]} to {symbols[num2]} : {bond_length_12:.3f}')
            
# if you only want to measure one time for each pair

for num1 in range(0,num_atoms):
    for num2 in range(0,num_atoms):
        if num1 < num2:
            x_distance = coordinates[num1,0] - coordinates[num2,0]
            y_distance = coordinates[num1,1] - coordinates[num2,1]
            z_distance = coordinates[num1,2] - coordinates[num2,2]
            bond_length_12 = numpy.sqrt(x_distance**2 + y_distance**2 + z_distance**2)
            if bond_length_12 > 0 and bond_length_12 < 1.5: # to not print the self-self measurements
                print(F'{symbols[num1]} to {symbols[num2]} : {bond_length_12:.3f}')

O to H1 : 0.969
O to H2 : 0.969
H1 to O : 0.969
H2 to O : 0.969
O to H1 : 0.969
O to H2 : 0.969


## Refactoring Code with Functions

In [19]:
# to reuse the above code, you would have to rewrite everything or cut and paste
# better to create a function that calculates a distance and call that function when you need it
# the most compelling reason to write function (code easier to read, code more reusable, MAKES CODE EASIER TO TEST)

# syntax for defining a function
# def function_name(parameters (inputs for the function to accept)):
#     function code goes here
#     could be multiple lines
#     return value_to_return

# function for calculating the distance between two atoms
# Start: forget where the data is coming from - what is the best way to do this math operation

def calculate_distance(atom1_coord, atom2_coord):
    """
    This function takes to coordinates of two atoms and calculates the distance between them.
    Inputs: atom1_coord, atom2_coord
    Return: distance
    """
    x_distance = atom1_coord[0] - atom2_coord[0]
    y_distance = atom1_coord[1] - atom2_coord[1]
    z_distance = atom1_coord[2] - atom2_coord[2]
    distance = numpy.sqrt(x_distance**2 + y_distance**2 + z_distance**2)
    return distance # must be something calculated in the body of code

# make sure to execute the cell when you define a function
# when defining a function, think about the simplest set of inputs and outputs
# when you want to use a function, think about the inputs you need to provide and the output you want to receive
# you can use a docstring to create a help entry for a function

In [14]:
for num1 in range(0,num_atoms):
    for num2 in range(0,num_atoms):
        if num1 < num2:
            bond_length_12 = calculate_distance(coordinates[num1], coordinates[num2])
            if bond_length_12 > 0 and bond_length_12 < 1.5: # to not print the self-self measurements
                print(F'{symbols[num1]} to {symbols[num2]} : {bond_length_12:.3f}')

O to H1 : 0.969
O to H2 : 0.969


In [20]:
help(calculate_distance)

Help on function calculate_distance in module __main__:

calculate_distance(atom1_coord, atom2_coord)
    This function takes to coordinates of two atoms and calculates the distance between them.
    Inputs: atom1_coord, atom2_coord
    Return: distance



In [29]:
# Write function called bond_check to check and see if a distance is between 0 and 1.5 angtroms.
# Return True or False

def bond_check(distance, minimum_length, maximum_length):
    """
    This function determines if a distance is between the specified minimum and maximum values. It returns true or false
    Input: distance, minimum_length, maximum_length
    Return: Boolean True or False
    """
    if distance > minimum_length and distance < maximum_length:
        return True
    else:
        return False
    

In [37]:
# Check the function
bond_check(1,0,1.6)

True

In [44]:
# Write function called bond_check to check and see if a distance is between 0 and 1.5 angtroms.
# Return True or False

def bond_check(distance, minimum_length=0, maximum_length=1.5):
    """
    This function determines if a distance is between the specified minimum and maximum values. 
    The specified minimum is 0 Angstroms and the default maximum value is 1.5 Angstroms.It returns true or false
    Input: distance, minimum_length, maximum_length
    Return: Boolean True or False
    """
    if distance > minimum_length and distance <= maximum_length:
        return True
    else:
        return False
    

In [35]:
bond_check(1)

True

In [42]:
bond_check(1.5,minimum_length=0)

True

In [46]:
for num1 in range(0,num_atoms):
    for num2 in range(0,num_atoms):
        if num1 < num2:
            bond_length_12 = calculate_distance(coordinates[num1], coordinates[num2])
            if bond_check(bond_length_12) is True:
                print(F'{symbols[num1]} to {symbols[num2]} : {bond_length_12:.3f}')

O to H1 : 0.969
O to H2 : 0.969


In [74]:
# Write a function that reads in and processes and xyz file.
# function name open_xyz
# Input filename
# Two outputs: symbols and coordinates

def open_xyz(file_location):
    """
    Opens and processes a standard format xyz file and returns two outputs: the symbols and a numpy array of coordinates
    """
    xyz_file = numpy.genfromtxt(fname = file_location, skip_header = 2, dtype = 'unicode')
    # you must use skip header to get rid of lines that don't contain the same number of columns
    
    # Separate data types
    symbols = xyz_file[:,0] #symbols are already strings
    coordinates = xyz_file[:,1:]
    coordinates = coordinates.astype(numpy.float)
    return symbols, coordinates

In [77]:
file_location = os.path.join('data', 'water.xyz')
molecule_symbols, molecule_coordinates = open_xyz(file_location)

In [78]:
print(molecule_symbols)

['O' 'H1' 'H2']


In [79]:
print(molecule_coordinates)

[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]


In [80]:
file_location = os.path.join('data', 'benzene.xyz')
molecule_symbols, molecule_coordinates = open_xyz(file_location)
print(molecule_symbols)
print(molecule_coordinates)

['C' 'H' 'C' 'H' 'C' 'H' 'C' 'H' 'C' 'H' 'C' 'H']
[[ 0.       1.40272  0.     ]
 [ 0.       2.49029  0.     ]
 [-1.21479  0.70136  0.     ]
 [-2.15666  1.24515  0.     ]
 [-1.21479 -0.70136  0.     ]
 [-2.15666 -1.24515  0.     ]
 [ 0.      -1.40272  0.     ]
 [ 0.      -2.49029  0.     ]
 [ 1.21479 -0.70136  0.     ]
 [ 2.15666 -1.24515  0.     ]
 [ 1.21479  0.70136  0.     ]
 [ 2.15666  1.24515  0.     ]]


In [84]:
import numpy
import os

def open_xyz(file_location):
    """
    Opens and processes a standard format xyz file and returns two outputs: the symbols and a numpy array of coordinates
    """
    xyz_file = numpy.genfromtxt(fname = file_location, skip_header = 2, dtype = 'unicode')
    # you must use skip header to get rid of lines that don't contain the same number of columns
    
    # Separate data types
    symbols = xyz_file[:,0] #symbols are already strings
    coordinates = xyz_file[:,1:]
    coordinates = coordinates.astype(numpy.float)
    return symbols, coordinates

def bond_check(distance, minimum_length=0, maximum_length=1.5):
    """
    This function determines if a distance is between the specified minimum and maximum values. 
    The specified minimum is 0 Angstroms and the default maximum value is 1.5 Angstroms.It returns true or false
    Input: distance, minimum_length, maximum_length
    Return: Boolean True or False
    """
    if distance > minimum_length and distance <= maximum_length:
        return True
    else:
        return False
    
def calculate_distance(atom1_coord, atom2_coord):
    """
    This function takes to coordinates of two atoms and calculates the distance between them.
    Inputs: atom1_coord, atom2_coord
    Return: distance
    """
    x_distance = atom1_coord[0] - atom2_coord[0]
    y_distance = atom1_coord[1] - atom2_coord[1]
    z_distance = atom1_coord[2] - atom2_coord[2]
    distance = numpy.sqrt(x_distance**2 + y_distance**2 + z_distance**2)
    return distance # must be something calculated in the body of code  

file_location = os.path.join('data', 'water.xyz')
symbols, coord = open_xyz(file_location)
num_atoms = len(symbols)
for num1 in range(0,num_atoms):
    for num2 in range(0,num_atoms):
        if num1<num2:
            bond_length_12 = calculate_distance(coord[num1], coord[num2])
            if bond_check(bond_length_12) is True:
                print(F'{symbols[num1]} to {symbols[num2]} : {bond_length_12:.3f}')

O to H1 : 0.969
O to H2 : 0.969
